### ISSUE TITLE
Star

### ISSUE THREAD

**Issue by 89z** [Neo-Oli/fantasymap#2]
Good afternoon, sorry to bother you. For some reason, many people are giving star to my repo:

https://github.com/89z/googleplay

I saw you gave my repo a star, thank you. However I don't know how its happening. Can you say how you found my project? Is it linked somewhere?

**Comment by Neo-Oli** [comment]
Hi, 

I found your project after [gplaydl](https://github.com/rehmatworks/gplaydl) broke for me (and [gplaycli](https://github.com/matlink/gplaycli) before that). I think I found the link in this issue: https://github.com/rehmatworks/gplaydl/issues/30#issuecomment-1006751166. Your tool fills this same need for me, to download apks from google play that I can use inside a script. I use it do install and update apps using [Termux](https://termux.com) on my Android phone (that doesn't have Google).

I guess a lot of people are finding your Tool becaus I think Google changed something about their API and things like gplaydl recently broke and your tool still works, and is, for now, well maintained.
